app = "conversme-backend"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

  [build.args]
    BUILDKIT_INLINE_CACHE="1"

  [build.cache]
    mode = "shared"
    layer_invalidation_policy = "dependencies"

[env]
  API_HOST = "0.0.0.0"
  API_PORT = "8080"
  DEBUG = "False"
  API_WORKERS = "2"
  DB_POOL_SIZE = "5"
  DB_MAX_OVERFLOW = "10"
  DB_POOL_TIMEOUT = "30"
  LOG_ALL_QUERIES = "False"
  ALGORITHM = "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES = "60"
  UPLOAD_DIR = "/app/uploads"
  MAX_UPLOAD_SIZE = "10485760"
  ALLOWED_EXTENSIONS = "jpg,jpeg,png,gif,mp3,mp4,wav,pdf,doc,docx"
  LOG_LEVEL = "INFO"
  FRONTEND_URL = "https://conversme-frontend.fly.dev"
  REDIRECT_URL = "https://conversme-frontend.fly.dev/auth/callback"
  # Redis and Tigris configuration
  CELERY_BROKER_URL = "${REDIS_URL}/1"
  CELERY_RESULT_BACKEND = "${REDIS_URL}/2"
  TIGRIS_URL = "${TIGRIS_URL}"
  TIGRIS_PROJECT = "conversme"
  TIGRIS_BUCKET = "media"
  USE_LOCAL_STORAGE = "False"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 500

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

  [[services.ports]]
    handlers = ["pg_tls"]
    port = 5432

[[statics]]
  guest_path = "/app/uploads"
  url_prefix = "/uploads"

[mounts]
  source = "conversme_uploads"
  destination = "/app/uploads"

# Recommended settings for small to medium traffic
[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

# Health check endpoint
[[http_service.checks]]
  interval = "30s"
  timeout = "5s"
  grace_period = "120s"
  method = "GET"
  path = "/health"
  protocol = "http"
