"""add_collection_id_to_directories

Revision ID: 2a31d1fc8eff
Revises: 1cc2ea36a2a4
Create Date: 2025-04-30 17:18:14.124102

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2a31d1fc8eff'
down_revision = '1cc2ea36a2a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('collection_id', sa.UUID(), nullable=True))
    op.create_index('idx_directories_collection_id', 'directories', ['collection_id'], unique=False)
    op.create_foreign_key(None, 'directories', 'library_collections', ['collection_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'directories', type_='foreignkey')
    op.drop_index('idx_directories_collection_id', table_name='directories')
    op.drop_column('directories', 'collection_id')
    # ### end Alembic commands ###
