"""add_is_template_to_directories

Revision ID: 5ef509ce59d8
Revises: 2a31d1fc8eff
Create Date: 2025-04-30 17:23:21.801090

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5ef509ce59d8'
down_revision = '2a31d1fc8eff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directories', sa.Column('is_template', sa.Boolean(), nullable=True))
    op.create_index('idx_directories_is_template', 'directories', ['is_template'], unique=False)

    # Update existing directories that belong to collections to be templates
    op.execute("""
    UPDATE directories
    SET is_template = TRUE
    WHERE collection_id IS NOT NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_directories_is_template', table_name='directories')
    op.drop_column('directories', 'is_template')
    # ### end Alembic commands ###
