"""add_library_schema_metadata

Revision ID: 856fe729115a
Revises: 2e2d7d3fee2e
Create Date: 2025-04-30 07:09:24.867905

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '856fe729115a'
down_revision = '2e2d7d3fee2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create library_collections table
    op.create_table('library_collections',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('saves', sa.Integer(), default=0, nullable=True),
        sa.Column('collection_metadata', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('created_by_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indices for library_collections
    op.create_index('idx_library_collections_created_by_id', 'library_collections', ['created_by_id'], unique=False)
    op.create_index('idx_library_collections_title', 'library_collections', ['title'], unique=False)

    # Add collection_id column to directories table
    op.add_column('directories',
        sa.Column('collection_id', sa.UUID(), nullable=True)
    )

    # Add foreign key constraint to directories.collection_id
    op.create_foreign_key(
        'fk_directories_collection_id',
        'directories',
        'library_collections',
        ['collection_id'],
        ['id'],
        ondelete='SET NULL'
    )

    # Create index for collection_id on directories
    op.create_index('idx_directories_collection_id', 'directories', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop added indices and constraints
    op.drop_index('idx_directories_collection_id', table_name='directories')
    op.drop_constraint('fk_directories_collection_id', 'directories', type_='foreignkey')
    op.drop_column('directories', 'collection_id')

    # Drop library collections table and indices
    op.drop_index('idx_library_collections_title', table_name='library_collections')
    op.drop_index('idx_library_collections_created_by_id', table_name='library_collections')
    op.drop_table('library_collections')
    # ### end Alembic commands ###
